// Generated by CoffeeScript 2.0.1
var TIMETRACKER;

TIMETRACKER = {
  Settings: {
    dataStorageKey: 'timetracker-data'
  },
  Data: {
    current: 'Default',
    data: []
  }
};

TIMETRACKER.AppViewModel = function() {
  var bindEvents, load, save, self;
  self = this;
  self.titles = ko.pureComputed(function() {
    return _.keys(TIMETRACKER.Data.data);
  });
  self.current = ko.pureComputed(function() {
    return TIMETRACKER.Data.current;
  });
  self.isSelectProject = ko.observable(false);
  load = function() {
    var data;
    data = window.localStorage.getItem(TIMETRACKER.Settings.dataStorageKey);
    if (data) {
      TIMETRACKER.Data = JSON.parse(data);
    }
    return null;
  };
  save = function() {
    var data;
    data = JSON.stringify(TIMETRACKER.Data);
    window.localStorage.setItem(TIMETRACKER.Settings.dataStorageKey, data);
    return null;
  };
  bindEvents = function() {
    //document.addEventListener 'mouseup', (e) ->
    //    self.isSelectProject false
    return null;
  };
  self.selectProjectClick = function(data, e) {
    e.preventDefault();
    e.stopPropagation();
    return null;
  };
  self.toggleSelectProject = function() {
    //if self.titles().length > 1
    //    self.isSelectProject !self.isSelectProject()
    self.isSelectProject(!self.isSelectProject());
    return null;
  };
  self.addProject = function() {
    var title;
    //if startDate
    //    return alert 'Нельзя добавить проект пока работает таймер'
    title = window.prompt('Введите название нового проекта:', '').trim();
    if (!title) {
      return window.alert('Вы не ввели название проекта');
    }
    if (self.titles().indexOf(title) !== -1) {
      return window.alert('Такой проект уже существует');
    }
    TIMETRACKER.Data.current = title;
    TIMETRACKER.Data.data[title] = [];
    save();
    //renderProjectSelectList()
    //setProject()
    return null;
  };
  self.removeProject = function() {
    //if startDate
    //    return window.alert 'Нельзя удалить проект пока работает таймер'
    if (window.confirm('Вы действительно хотите БЕЗВОЗВРАТНО удалить проект?')) {
      if (TIMETRACKER.Data.current === 'Default') {
        return window.alert('Нельзя удалить проект `Default`');
      }
      delete TIMETRACKER.Data.data[TIMETRACKER.Data.current];
      TIMETRACKER.Data.current = 'Default';
      save();
    }
    //renderProjectSelectList()
    //setProject()
    return null;
  };
  load();
  bindEvents();
  return self;
};

window.onload = function() {
  return ko.applyBindings(new TIMETRACKER.AppViewModel(), document.getElementById('content-wrapper'));
};
